### ISSUE TITLE
[FTR-002] Improve forms experience

### ISSUE THREAD

**Issue by OneLiL05** [discursa/discursa#5]
**TODO:**
---

- [x] Add `Cancel` button to create item forms;
- [x] Disable `Create` button at forms when inputs' values are empty.
- [x] Add autofocus to first input in forms.
