### ISSUE TITLE
[RFT-003] Write auth business logic for auth with new architecture

### ISSUE THREAD

**Issue by OneLiL05** [discursa/discursa#6]
**TODO:**
---

- [x] Write service for auth module;
- [x] Write types for service;
- [x] Write business logic in custom hooks;
- [x] Migrate auth module on new architecture.
